theme: jekyll-theme-cayman
github:
  is_project_page: false
title: CYS Secure Biometrics Competition 2022
tagline: Open the door to encrypted access control<br>Organized by the CYS group of the Delft University of Technology
